service: book-quote
frameworkVersion: '3'
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: npm
    concurrency: 4
  serverless-offline:
    httpPort: 3003
  dynamodb:
    start:
      port: 5000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: ${self:provider.environment.USERS_TABLE}
            sources:
              - ./test/users.json
    stages:
      - dev
package:
  individually: true
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    apiKeys:
      - ${self:provider.stage}-book-quote
    usagePlan:
      quota:
        limit: 1000
        offset: 0
        period: DAY
      throttle:
        burstLimit: 100
        rateLimit: 10
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    USERS_TABLE: users-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - sqs:*
            - s3:*
          Resource:
            - Fn::GetAtt:
                - UsuariosTable
                - Arn
functions:
  - ${file(serverless/user/functions.yml)}
resources:
  - ${file(serverless/user/resources.yml)}
